'use client';

import React, { useState, useRef } from 'react';
import Head from 'next/head';
import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';

// --- 结果展示弹窗 (增强版：支持导出 PDF) ---
const ResultModal: React.FC<{ content: string; onClose: () => void }> = ({ content, onClose }) => {
  const reportRef = useRef<HTMLDivElement>(null);
  const [isExporting, setIsExporting] = useState(false);

  const downloadPDF = async () => {
    if (!reportRef.current) return;
    setIsExporting(true);
    
    const canvas = await html2canvas(reportRef.current, { scale: 2 });
    const imgData = canvas.toDataURL('image/png');
    const pdf = new jsPDF('p', 'mm', 'a4');
    const pdfWidth = pdf.internal.pageSize.getWidth();
    const pdfHeight = (canvas.height * pdfWidth) / canvas.width;
    
    pdf.addImage(imgData, 'PNG', 0, 0, pdfWidth, pdfHeight);
    pdf.save(`Insight_Engine_诊断报告_${new Date().getTime()}.pdf`);
    setIsExporting(false);
  };

  return (
    <div style={{ position: 'fixed', top: 0, left: 0, right: 0, bottom: 0, backgroundColor: 'rgba(0,0,0,0.15)', backdropFilter: 'blur(12px)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 100, padding: '20px' }}>
      <div style={{ maxWidth: '800px', width: '100%', position: 'relative' }}>
        {/* 报告主体 (将被截图) */}
        <div ref={reportRef} style={{ backgroundColor: '#fff', borderRadius: '24px', padding: '40px', boxShadow: '0 20px 50px rgba(0,0,0,0.1)', border: '1px solid #F3EAE3' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '30px', borderBottom: '2px solid #F8F9FA', paddingBottom: '20px' }}>
            <div>
              <h2 style={{ color: '#BC8F8F', margin: 0, fontSize: '24px' }}>AI 深度诊断报告</h2>
              <p style={{ color: '#94A3B8', fontSize: '12px', margin: '5px 0 0' }}>Generated by Insight Engine • {new Date().toLocaleDateString()}</p>
            </div>
            <div style={{ fontSize: '30px', opacity: 0.2 }}>🧠</div>
          </div>
          
          <div style={{ lineHeight: '1.8', color: '#475569', whiteSpace: 'pre-wrap', fontSize: '15px' }}>
            {content}
          </div>
          
          <div style={{ marginTop: '40px', paddingTop: '20px', borderTop: '1px dashed #EEDCDB', textAlign: 'center' }}>
            <p style={{ color: '#BC8F8F', fontSize: '13px', fontStyle: 'italic' }}>“让数据拥有温度，让品牌更懂人心。”</p>
          </div>
        </div>

        {/* 操作按钮区 (不包含在 PDF 内) */}
        <div style={{ marginTop: '20px', display: 'flex', gap: '15px', justifyContent: 'center' }}>
          <button 
            onClick={downloadPDF} 
            disabled={isExporting}
            style={{ padding: '12px 24px', backgroundColor: '#BC8F8F', color: 'white', borderRadius: '12px', border: 'none', cursor: 'pointer', fontWeight: '600', transition: 'all 0.2s' }}
          >
            {isExporting ? '正在生成 PDF...' : '⬇️ 下载 PDF 报告'}
          </button>
          <button 
            onClick={onClose} 
            style={{ padding: '12px 24px', backgroundColor: 'white', color: '#64748B', borderRadius: '12px', border: '1px solid #E1E8EB', cursor: 'pointer' }}
          >
            关闭预览
          </button>
        </div>
      </div>
    </div>
  );
};

// ... 其余 Page 组件代码保持不变 (确保 handleStartAnalysis 逻辑正确) ...